server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    basedir: /temp/approval
    max-threads: 2000
    min-spare-threads: 10
    accesslog:
      pattern: common
      enabled: true
      directory: logs
      prefix: jeeplus_access_log
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
  servlet:
    #修改项目访问路径
    context-path: /approval
logging:
  level:
    root: INFO
    #    org.flowable: DEBUG
    com.jeeplus: DEBUG
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN
spring:
  servlet:
    multipart:
      maxFileSize:  1000MB
      maxRequestSize: 1000MB
  devtools:
    restart:
      enabled: true
  #  profiles:
  #    active: dev
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #  jpa:
  #    open-in-view: false
  datasource:
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        validation-query: select 'x'
        SelectMethod: cursor
        filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall
      p6spy: false # 默认false,线上必须关闭。开发阶段可以打开调试输出mybatis语句，但是有许多莫名其妙的bug，以及严重的性能问题，所以正式环境必须关闭。
      datasource:
        master:
          #username: root
          #password: 123456
          #url: jdbc:mysql://gmfzhimi.oicp.io:29823/digital_guilin?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT&allowMultiQueries=true
          #url: jdbc:mysql://192.168.2.136:3306/flow?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=GMT&allowMultiQueries=true
          
          #username: zhimi
          #password: zhimi@123
          #url: jdbc:mysql://rm-wz9w577q07r007727hm.mysql.rds.aliyuncs.com:3306/digital_guilin?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
          
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1:3306/flow?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&autoReconnect=true&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          
          #oracle database settings
          #            username: monitor
          #            password: monitor
          #            url: jdbc:oracle:thin:@127.0.0.1:1521:helowin
          #            driver-class-name: oracle.jdbc.driver.OracleDriver


          ##mssql database settings
          #            username: sa
          #            password: yourStrong(!)Password
          #            driver-class-name: net.sourceforge.jtds.jdbc.Driver
          #            url: jdbc:jtds:sqlserver://localhost:1433;SelectMethod=cursor;DatabaseName=jeeplus
          #            SelectMethod: cursor
          #            testSql: SELECT 'x'


          ##pg database settings
  #            username: postgres
  #            password: password
  #            driver-class-name: org.postgresql.Driver
  #            url: jdbc:postgresql://localhost:5432/jeeplus-boot-pg
  #            testSql: SELECT 'x'
  # if you need use pg database , please enable this config.
  #  jpa:
  #    properties:
  #      hibernate:
  #        jdbc:
  #          lob:
  #            non_contextual_creation: true
  #spring-ehcache的配置
  cache:
    type: ehcache # redis/ehcache， 在这里设置你使用的缓存框架，如果不想使用redis，请改成ehcache
  ehcache:
    config: classpath:ehcache.xml
  redis:
    database: 20
    host: localhost
    port: 6379
    expireTime: 3600000 #单位秒
  mvc.servlet.load-on-startup: 1
  jmx:
    enabled: false
  # quartz任务配置
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=
      tablePrefix: QRTZ_
      isClustered: false # 打开集群配置
      clusterCheckinInterval: 2000 # 设置集群检查间隔20s
      useProperties: false
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 10
      threadPriority: 5
      threadsInheritContextClassLoaderOfInitializingThread: true
flowable:
  # 关闭定时任务Job
  async-executor-activate: false
  check-process-definitions: false
  process-definition-location-prefix: classpath:/processes/
  database-schema-update: false
  common:
    app:
      idm-url: http://localhost:9999
      idm-admin:
        user: admin
        password: test
#mybatis的配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
    - classpath*:com/jeeplus/modules/**/*Mapper.xml
    - classpath:/META-INF/admin-mybatis-mappings/*.xml
    - classpath:/META-INF/modeler-mybatis-mappings/*.xml
  type-aliases-package: com.jeeplus.modules
  configuration-properties:
    prefix:
    boolValue: TRUE
    blobType: BLOB
#oss配置
config:
  accessory:
    type: azureBlob       #local, aliyun, minIO ,azureBlob
    baseDir: file
    local:
     location: d:\\accessory
    aliyun:
     endpoint: oss-cn-hangzhou.aliyuncs.com
     accessKeyId: LTAI4Fhraue2ayc1KQMkZz5F
     accessKeySecret: hMpiD9KXcuWNMgzZxFt1fXK0gRMR70
     bucketName: testajgw
    minIO:
     endpoint:
     accessKey:
     secretKey:
     bucketName:
    azureBlob:
     serverUrl: 'https://bowkerstorage.blob.core.windows.net'
     blobName: commontools
     connectionString: 'DefaultEndpointsProtocol=https;AccountName=bowkerstorage;AccountKey=i9cQSmIHnrqbGOGQnT1laRSxMS+TcOHYrJz0r9nevygrJH9c7RruvS/hs+JJm+WvwbjUxt/o2X6dr84OslysZQ==;EndpointSuffix=core.windows.net'
#wps配置
wps:
  appid: 
  appsecret: 
  download_host: http://xxxxxx.org/jeeplus-vue
  domain: https://wwo.wps.cn
  downloadCallbackPath: /usr/local/wps
  webctx: /jeeplus-vue

#import export
ie:
 dealPoolSize: 10
#============================#
#===== System settings ======#
#============================#

#产品信息设置
productName: gmfmes
copyrightYear: 2020
version: V-1.0
allowLoginkey: 
# 为空 ， bowker_baseportal , gmf_center , cas
ssoType: bowker_baseportal
#演示模式: 不能操作和保存的模块： sys
demoMode: false
#上传文件绝对路径, 路径中不允许包含“userfiles”   【占锐： 如果是 /opt/jeeplusdir   这种相对路径，会在项目所在磁盘根目录下创建/opt/jeeplusdir 文件夹】
#userfiles.basedir: C:\\Users\\Administrator\\Desktop\\lib\\epin\\apache-tomcat-8.0.51\\webapps\\userfiles  #lewis_liu配置，请不要删除下面的配置，注释掉即可
userfiles:
  basedir:       # 文件上传路径，可以留空
  allowedType: file  # 允许上传的文件类型， all, file ,image, audio, video, office
  extensions:
    all: all       # 允许上传所有类型文件
    file: 7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip       # 只允许上传安全文件（linux系统非可执行）
    image: gif,jpg,jpeg,bmp,png     # 只允许上传图片
    audio: CD,OGG,MP3,ASF,WMA,WAV,MP3PRO,RM,REAL,APE,MODULE,MIDI,VQF    # 只允许上传音频
    video: AVI,WMV,RM,RMVB,MPEG1,MPEG2,MPEG4(MP4),3GP,ASF,SWF,VOB,DAT,MOV,M4V,FLV,F4V,MKV,MTS,TS     # 只允许上传视频
    office: txt,xls,xlsx,xlsm,xltx,xltm,xlsb,xlam,doc,docx,docm,dotx,dotm,ppt,pptx,pptm,ppsx,ppsm,potx,potm,ppam     # 只允许上传office文件
#JWT access token过期时间（access过期时间，并不是指需要重新登录的超时时间，而是指需要刷新重新获取access token的时间，超时登录的时间是3*EXPIRE_TIME，即refresh token的有效时时间)
jwt.accessToken.expireTime: 86400000 # 24小时，单位毫秒


#===============================#
#====== license 信息 ================#
#===============================#

# 产品授权 - 
productId: Y2020010392
license: 0BFBF004A11CB6B68E34F3B9440ED770C349C20E6E9F0EA4CF1F5F255FEF4874A07FADD423295DD848ED0263F215456ACF52D257F211320624AB4BA56EF9D0AC



#=======================================================================#
#===== plugin设置 =====#
#Plugin插件会读取该core和admin包下的基础类，如果修改了路径或者类名，请同步修改这里
#=======================================================================#
plugin:
  Page: com.jeeplus.core.persistence.Page
  User: com.jeeplus.modules.sys.entity.User
  Area: com.jeeplus.modules.sys.entity.Area
  Office: com.jeeplus.modules.sys.entity.Office
  UserUtils: com.jeeplus.modules.sys.utils.UserUtils



